CREATE TABLE IF NOT EXISTS gauges (
    id VARCHAR(255) PRIMARY KEY,
    value DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS counters (
    id VARCHAR(255) PRIMARY KEY,
    delta BIGINT NOT NULL
);